const GITHUB_URL = 'https://github.com/rowant-labs/classroompanel';

export const metadata = { title: 'ClassroomPanel — Terms & Privacy' };

export default function TermsPage() {
  return (
    <main className="page-shell legal-shell">
      <section className="hero">
        <div className="eyebrow">ClassroomPanel / Terms &amp; Privacy</div>
        <h1>The deal, in plain language.</h1>
        <p>
          ClassroomPanel is free, open-source learning software. These terms cover the hosted service at
          classroompanel.com (the “Service”). Using the Service means you accept them; if you do not accept
          them, do not use the Service. This page is version-controlled with the code — its{' '}
          <a href={`${GITHUB_URL}/commits/main/app/terms/page.tsx`}>git history</a> is its changelog.
        </p>
      </section>

      <div className="vision-flow legal-flow">
        <section className="vision-card">
          <h2>Lessons are AI-generated. Verify what matters.</h2>
          <p>
            Every lesson, picture, quiz, and piece of feedback is generated by an AI model at the moment you ask
            for it. AI models make mistakes — confidently. We do not review, endorse, or guarantee the accuracy,
            completeness, safety, or fitness of any generated content. The Service is a learning aid, not a
            substitute for a qualified teacher, curriculum authority, or professional advice of any kind
            (educational, medical, legal, financial, or otherwise). An adult should supervise a child’s use and
            apply their own judgment to what the board teaches.
          </p>
        </section>

        <section className="vision-card">
          <h2>Children use this with a parent or guardian.</h2>
          <p>
            The Service is designed for family learning under adult supervision. If you are under 18, use the
            Service only with the permission and supervision of a parent or legal guardian; the guardian is the
            user these terms address, and they are responsible for the child’s use. We collect no personal
            information from anyone — including children — so there is nothing for us to know about who is
            learning.
          </p>
        </section>

        <section className="vision-card">
          <h2>Your key, your provider, your responsibility.</h2>
          <p>
            Live generation runs on a model API key <strong>you</strong> supply. Your key is sent with each
            generation request you trigger, used for that request, and never stored or logged by the Service —
            the code that handles it is public and auditable. Everything about your key remains yours: your
            provider account, your provider’s terms of service, the costs your usage incurs, and keeping the key
            secret. We are not a party to your relationship with Anthropic, OpenAI, Google, or any other
            provider, and we are not responsible for their availability, pricing, content, or conduct. Treat a
            key like money: use spending caps in your provider’s console, and revoke any key you believe was
            exposed.
          </p>
        </section>

        <section className="vision-card">
          <h2>We collect nothing. Your data never reaches us.</h2>
          <p>
            The Service has no accounts, no sign-in, no analytics, no tracking cookies, and no server-side
            storage of your content. Lessons, uploaded curriculum, API keys, quiz answers, and the learner
            record are processed transiently to serve the request you made and are not retained. The learner
            record lives only in your browser’s local storage and in files you export — which also means{' '}
            <strong>backing it up is your responsibility</strong>: clearing your browser data erases it, so use
            Export regularly. (One technical note: generated board images are cached briefly, keyed by the text
            of the prompt that produced them — never by who asked.) Because we collect no personal information
            from anyone, we have nothing to sell, share, lose, or be compelled to hand over.
          </p>
        </section>

        <section className="vision-card">
          <h2>Provided as-is. No warranty. No liability.</h2>
          <p>
            The Service is provided free of charge, <strong>“as is” and “as available,”</strong> without
            warranties of any kind, express or implied — including, without limitation, warranties of
            merchantability, fitness for a particular purpose, accuracy, non-infringement, and uninterrupted or
            error-free operation. We may change, suspend, or discontinue any part of the Service at any time
            without notice.
          </p>
          <p>
            To the fullest extent permitted by law, the maintainer, contributors, and operators of the Service
            are not liable for any damages of any kind arising from or related to your use of (or inability to
            use) the Service — including direct, indirect, incidental, consequential, special, exemplary, or
            punitive damages; lost data (including a lost learner record); educational outcomes; or charges
            incurred with your model provider. Your sole and exclusive remedy for any dissatisfaction with the
            Service is to stop using it. If applicable law does not permit some of these exclusions, our total
            aggregate liability is limited to the amount you paid us to use the Service — which is zero. You
            agree to hold the maintainer and contributors harmless from claims arising out of your misuse of the
            Service or your violation of these terms.
          </p>
        </section>

        <section className="vision-card">
          <h2>Use it honestly.</h2>
          <p>
            Don’t use the Service for anything unlawful, don’t attempt to disrupt or overload it, don’t probe or
            abuse the systems it runs on, and don’t use it to violate your model provider’s terms. We may block
            abusive traffic at our discretion.
          </p>
        </section>

        <section className="vision-card">
          <h2>The code is yours. The name is ours.</h2>
          <p>
            The ClassroomPanel software is licensed under the{' '}
            <a href={`${GITHUB_URL}/blob/main/LICENSE`}>AGPL-3.0</a>. Nothing in these terms limits any right
            that license grants you — read it, run it, modify it, self-host it. Self-hosted instances are
            operated by whoever runs them and are entirely their responsibility; these terms cover only
            classroompanel.com, the sole instance operated by the maintainer. “ClassroomPanel” and its logo are
            project trademarks: forks are welcome and must use their own name.
          </p>
        </section>

        <section className="vision-card">
          <h2>Housekeeping.</h2>
          <p>
            We may update these terms; the change lands in the public git history, and continued use of the
            Service after a change means you accept it. These terms are governed by the laws of the United
            States and the State of Texas, without regard to conflict-of-law rules. If any
            part of these terms is found unenforceable, the rest still applies. Questions or concerns:{' '}
            <a href={`${GITHUB_URL}/issues`}>open an issue on GitHub</a>.
          </p>
          <div className="hero-actions">
            <a href="/panel" className="primary">Open the learning terminal</a>
            <a href="/" className="secondary">Back to the vision</a>
          </div>
        </section>
      </div>
    </main>
  );
}
